basePath: /
definitions:
  dto_book.Create:
    properties:
      name:
        type: string
      page:
        type: integer
    required:
    - name
    - page
    type: object
  dto_book.Full:
    properties:
      _id:
        type: string
      created_at:
        type: string
      name:
        type: string
      page:
        type: integer
      updated_at:
        type: string
    type: object
  dto_book.List:
    properties:
      count:
        type: string
      page:
        type: string
    type: object
  dto_book.Summary:
    properties:
      books:
        items:
          $ref: '#/definitions/dto_book.Full'
        type: array
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a Jettster service APIs.
  license: {}
  title: Jettster Swagger API
  version: "1.0"
paths:
  /book:
    get:
      parameters:
      - in: query
        name: count
        type: string
      - in: query
        name: page
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto_book.Summary'
      summary: List of Books
    post:
      consumes:
      - application/json
      operationId: create-book
      parameters:
      - description: the request body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto_book.Create'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto_book.Full'
      summary: Create Book
  /book/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: url params
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto_book.Full'
      summary: Single Book
swagger: "2.0"
